- เครื่องออกกำลังกายทุกเครื่อง ใช้ cube ทำเป็นแท่ง ละ subdivide ให้กลม loop cut(ctrl + R ) ละดึงไปทางปลายไม่ให้แหลม ละเอาแต่ละแท่งมา join กัน
- โซ่ตรงชิงช้า ใช้ cube ทำ 6 เหลี่ยม ละ boolean เจาะรูตรงกลาง ทำ 1 คู่ละใช้ array ต่อกันเป็นเส้น
- หม้อ ใช้ circle ทำ extrude ละใช้ cube ทำด้ามจับละเอามาต่อ
- ฝาหม้อ ใช้ circle ทำ extrude
- ขวด ใช้ cylinder ทำ loop cut หลายๆชั้น ละ scale บางชั้นให้มีขนาดแตกต่างกัน (ความคอดของขวด) ลบ face ด้านบนของ cylinder ละ extrude ทำปากขวด  ทำ subdivide ให้กลม ฝาขวดใช้ cylinder ทำเหมือนขวด

